#pragma once

#include <cstdint>
#include <string>

enum KError : int16_t
{
    ErrUnknown = -1,
    ErrNoError = 0,
    ErrOffsetOutOfRange = 1,
    ErrInvalidMessage = 2,
    ErrUnknownTopicOrPartition = 3,
    ErrInvalidMessageSize = 4,
    ErrLeaderNotAvailable = 5,
    ErrNotLeaderForPartition = 6,
    ErrRequestTimedOut = 7,
    ErrBrokerNotAvailable = 8,
    ErrReplicaNotAvailable = 9,
    ErrMessageSizeTooLarge = 10,
    ErrStaleControllerEpochCode = 11,
    ErrOffsetMetadataTooLarge = 12,
    ErrNetworkException = 13,
    ErrOffsetsLoadInProgress = 14,
    ErrConsumerCoordinatorNotAvailable = 15,
    ErrNotCoordinatorForConsumer = 16,
    ErrInvalidTopic = 17,
    ErrMessageSetSizeTooLarge = 18,
    ErrNotEnoughReplicas = 19,
    ErrNotEnoughReplicasAfterAppend = 20,
    ErrInvalidRequiredAcks = 21,
    ErrIllegalGeneration = 22,
    ErrInconsistentGroupProtocol = 23,
    ErrInvalidGroupId = 24,
    ErrUnknownMemberId = 25,
    ErrInvalidSessionTimeout = 26,
    ErrRebalanceInProgress = 27,
    ErrInvalidCommitOffsetSize = 28,
    ErrTopicAuthorizationFailed = 29,
    ErrGroupAuthorizationFailed = 30,
    ErrClusterAuthorizationFailed = 31,
    ErrInvalidTimestamp = 32,
    ErrUnsupportedSASLMechanism = 33,
    ErrIllegalSASLState = 34,
    ErrUnsupportedVersion = 35,
    ErrTopicAlreadyExists = 36,
    ErrInvalidPartitions = 37,
    ErrInvalidReplicationFactor = 38,
    ErrInvalidReplicaAssignment = 39,
    ErrInvalidConfig = 40,
    ErrNotController = 41,
    ErrInvalidRequest = 42,
    ErrUnsupportedForMessageFormat = 43,
    ErrPolicyViolation = 44,
    ErrOutOfOrderSequenceNumber = 45,
    ErrDuplicateSequenceNumber = 46,
    ErrInvalidProducerEpoch = 47,
    ErrInvalidTxnState = 48,
    ErrInvalidProducerIDMapping = 49,
    ErrInvalidTransactionTimeout = 50,
    ErrConcurrentTransactions = 51,
    ErrTransactionCoordinatorFenced = 52,
    ErrTransactionalIDAuthorizationFailed = 53,
    ErrSecurityDisabled = 54,
    ErrOperationNotAttempted = 55,
    ErrKafkaStorageError = 56,
    ErrLogDirNotFound = 57,
    ErrSASLAuthenticationFailed = 58,
    ErrUnknownProducerID = 59,
    ErrReassignmentInProgress = 60,
    ErrDelegationTokenAuthDisabled = 61,
    ErrDelegationTokenNotFound = 62,
    ErrDelegationTokenOwnerMismatch = 63,
    ErrDelegationTokenRequestNotAllowed = 64,
    ErrDelegationTokenAuthorizationFailed = 65,
    ErrDelegationTokenExpired = 66,
    ErrInvalidPrincipalType = 67,
    ErrNonEmptyGroup = 68,
    ErrGroupIDNotFound = 69,
    ErrFetchSessionIDNotFound = 70,
    ErrInvalidFetchSessionEpoch = 71,
    ErrListenerNotFound = 72,
    ErrTopicDeletionDisabled = 73,
    ErrFencedLeaderEpoch = 74,
    ErrUnknownLeaderEpoch = 75,
    ErrUnsupportedCompressionType = 76,
    ErrStaleBrokerEpoch = 77,
    ErrOffsetNotAvailable = 78,
    ErrMemberIdRequired = 79,
    ErrPreferredLeaderNotAvailable = 80,
    ErrGroupMaxSizeReached = 81,
    ErrFencedInstancedId = 82,
    ErrEligibleLeadersNotAvailable = 83,
    ErrElectionNotNeeded = 84,
    ErrNoReassignmentInProgress = 85,
    ErrGroupSubscribedToTopic = 86,
    ErrInvalidRecord = 87,
    ErrUnstableOffsetCommit = 88,
    ErrThrottlingQuotaExceeded = 89,
    ErrProducerFenced = 90,
    ErrLittleEnd,

    ErrIOEOF = 1000,
    ErrTimedOut,
    ErrOutOfBrokers,
    ErrBrokerNotFound,
    ErrInvalidBrokerId,
    ErrClosedClient,
    ErrIncompleteResponse,
    ErrInvalidPartition,
    ErrAlreadyConnected,
    ErrNotConnected,
    ErrInsufficientData,
    ErrShuttingDown,
    ErrMessageTooLarge,
    ErrConsumerOffsetNotAdvanced,
    ErrConsumerOffsetUnsupportedVersion,
    ErrControllerNotAvailable,
    ErrNoTopicsToUpdateMetadata,
    ErrUnknownScramMechanism,
    ErrReassignPartitions,
    ErrDeleteRecords,
    ErrCreateACLs,
    ErrAddPartitionsToTxn,
    ErrTxnOffsetCommit,
    ErrTransactionNotReady,
    ErrNonTransactedProducer,
    ErrTransitionNotAllowed,
    ErrCannotTransitionNilError,
    ErrTxnUnableToParseResponse,
    ErrTopicUnkonw,
    ErrTopicNoDetails,
    ErrProducerRetryBufferOverflow,
    ErrUnsupportedRecordBatchVersion,
    ErrVariantOverflow,
    ErrTaggedFieldsInNonFlexibleContext,
    ErrInvalidStringLength,
    ErrUVariantOverflow,
    ErrInvalidArrayLength,
    ErrInvalidBool,
    ErrValidByteSliceLength,
    ErrNoConfiguredBrokers,
    ErrHeaderVersionIsOld,
    ErrPacketDecodingError,
    ErrInvalidClientID,
    ErrEncodeError,
    ErrDecodeError,
    ErrInvalidConsumer,
    ErrClosedConsumerGroup,
    ErrorGroupClosed,
    ErrTopicsProvided,
    ErrPacketEncoding,
    ErrTopicPartitionConsumed,
    ErrPermitForbidden,
    ErrMaxMessageBytes,
    ErrThrottled,
    ErrAlterClientQuotas,
    ErrDescribeClientQuotas,
    ErrClearupError,
    ErrInvalidCRCTYPE,
    ErrCRCMismatch,
    ErrUnknownRecordsType,
    ErrSyncProducerError,
    ErrSyncProducerSuccess,
    ErrStrategyNotFound,
    ErrUnknownMessage,

};

const char *KErrorToString(KError err);
template <class T>
auto KErrorToString(T err)
{
    return KErrorToString(static_cast<KError>(err));
}
bool IsKError(KError err);
template <class T>
auto IsKError(T err)
{
    return IsKError(static_cast<KError>(err));
}
template <typename T>
bool errorsIs(T a, T b) { return a == b; }
