/*
 *	coev - c++20 coroutine library
 *
 *	Copyright (c) 2023-2026, Zhao Yun Shan
 *
 */
#pragma once

#define ZOO_NOTIFY_OP 0
#define ZOO_CREATE_OP 1
#define ZOO_DELETE_OP 2
#define ZOO_EXISTS_OP 3
#define ZOO_GETDATA_OP 4
#define ZOO_SETDATA_OP 5
#define ZOO_GETACL_OP 6
#define ZOO_SETACL_OP 7
#define ZOO_GETCHILDREN_OP 8
#define ZOO_SYNC_OP 9
#define ZOO_PING_OP 11
#define ZOO_GETCHILDREN2_OP 12
#define ZOO_CHECK_OP 13
#define ZOO_MULTI_OP 14
#define ZOO_CREATE2_OP 15
#define ZOO_RECONFIG_OP 16
#define ZOO_CHECK_WATCHES 17
#define ZOO_REMOVE_WATCHES 18
#define ZOO_CREATE_CONTAINER_OP 19
#define ZOO_DELETE_CONTAINER_OP 20
#define ZOO_CREATE_TTL_OP 21
#define ZOO_CLOSE_OP -11
#define ZOO_SETAUTH_OP 100
#define ZOO_SETWATCHES_OP 101
#define ZOO_SASL_OP 102

#define ZOOKEEPER_WRITE (1 << 0)
#define ZOOKEEPER_READ (1 << 1)

#define ZOO_PERSISTENT 0
#define ZOO_EPHEMERAL 1
#define ZOO_PERSISTENT_SEQUENTIAL 2
#define ZOO_EPHEMERAL_SEQUENTIAL 3
#define ZOO_CONTAINER 4
#define ZOO_PERSISTENT_WITH_TTL 5
#define ZOO_PERSISTENT_SEQUENTIAL_WITH_TTL 6

#define WATCHER_EVENT_XID -1
#define PING_XID -2
#define AUTH_XID -4
#define SET_WATCHES_XID -8

#define EXPIRED_SESSION_STATE_DEF -112
#define AUTH_FAILED_STATE_DEF -113
#define CONNECTING_STATE_DEF 1
#define ASSOCIATING_STATE_DEF 2
#define CONNECTED_STATE_DEF 3
#define READONLY_STATE_DEF 5
#define SSL_CONNECTING_STATE_DEF 7
#define NOTCONNECTED_STATE_DEF 999

#define CREATED_EVENT_DEF 1
#define DELETED_EVENT_DEF 2
#define CHANGED_EVENT_DEF 3
#define CHILD_EVENT_DEF 4
#define SESSION_EVENT_DEF -1
#define NOTWATCHING_EVENT_DEF -2

#define ZOO_EXPIRED_SESSION_STATE EXPIRED_SESSION_STATE_DEF
#define ZOO_AUTH_FAILED_STATE AUTH_FAILED_STATE_DEF
#define ZOO_CONNECTING_STATE CONNECTING_STATE_DEF
#define ZOO_ASSOCIATING_STATE ASSOCIATING_STATE_DEF
#define ZOO_CONNECTED_STATE CONNECTED_STATE_DEF
#define ZOO_READONLY_STATE READONLY_STATE_DEF
#define ZOO_SSL_CONNECTING_STATE SSL_CONNECTING_STATE_DEF
#define ZOO_NOTCONNECTED_STATE NOTCONNECTED_STATE_DEF

#define ZOO_CREATED_EVENT CREATED_EVENT_DEF
#define ZOO_DELETED_EVENT DELETED_EVENT_DEF
#define ZOO_CHANGED_EVENT CHANGED_EVENT_DEF
#define ZOO_CHILD_EVENT CHILD_EVENT_DEF
#define ZOO_SESSION_EVENT SESSION_EVENT_DEF
#define ZOO_NOTWATCHING_EVENT NOTWATCHING_EVENT_DEF

#define ZOO_PERM_READ (1 << 0)
#define ZOO_PERM_WRITE (1 << 1)
#define ZOO_PERM_CREATE (1 << 2)
#define ZOO_PERM_DELETE (1 << 3)
#define ZOO_PERM_ADMIN (1 << 4)
#define ZOO_PERM_ALL (0x1f)

#define ZOO_READONLY 1
#define ZOO_NO_LOG_CLIENTENV 2

#define HANDSHAKE_REQ_SIZE (45)

#define ZOOKEEPER_IS_SEQUENCE(mode)         \
    ((mode) == ZOO_PERSISTENT_SEQUENTIAL || \
     (mode) == ZOO_EPHEMERAL_SEQUENTIAL ||  \
     (mode) == ZOO_PERSISTENT_SEQUENTIAL_WITH_TTL)
#define ZOOKEEPER_IS_TTL(mode)            \
    ((mode) == ZOO_PERSISTENT_WITH_TTL || \
     (mode) == ZOO_PERSISTENT_SEQUENTIAL_WITH_TTL)

#define HAVE_CYRUS_SASL_H 1
#define HAVE_OPENSSL_H 1

#define COMPLETION_WATCH -1
#define COMPLETION_VOID 0
#define COMPLETION_STAT 1
#define COMPLETION_DATA 2
#define COMPLETION_STRINGLIST 3
#define COMPLETION_STRINGLIST_STAT 4
#define COMPLETION_ACLLIST 5
#define COMPLETION_STRING 6
#define COMPLETION_MULTI 7
#define COMPLETION_STRING_STAT 8
#define ZOO_MAX_TTL 0xFFFFFFFFFFLL

#define ZOO_CONFIG_NODE "/zookeeper/config"

#ifdef __linux__
#define SEND_FLAGS MSG_NOSIGNAL
#endif
#ifndef SEND_FLAGS
#define SEND_FLAGS 0
#endif
enum ZOO_ERRORS
{
    ZOK = 0,

    ZSYSTEMERROR = -1,
    ZRUNTIMEINCONSISTENCY = -2,
    ZDATAINCONSISTENCY = -3,
    ZCONNECTIONLOSS = -4,
    ZMARSHALLINGERROR = -5,
    ZUNIMPLEMENTED = -6,
    ZOPERATIONTIMEOUT = -7,
    ZBADARGUMENTS = -8,
    ZINVALIDSTATE = -9,
    ZNEWCONFIGNOQUORUM = -13,
    ZRECONFIGINPROGRESS = -14,

    ZSSLCONNECTIONERROR = -15,

    ZAPIERROR = -100,
    ZNONODE = -101,
    ZNOAUTH = -102,
    ZBADVERSION = -103,
    ZNOCHILDRENFOREPHEMERALS = -108,
    ZNODEEXISTS = -110,
    ZNOTEMPTY = -111,
    ZSESSIONEXPIRED = -112,
    ZINVALIDCALLBACK = -113,
    ZINVALIDACL = -114,
    ZAUTHFAILED = -115,
    ZCLOSING = -116,
    ZNOTHING = -117,
    ZSESSIONMOVED = -118,
    ZNOTREADONLY = -119,
    ZEPHEMERALONLOCALSESSION = -120,
    ZNOWATCHER = -121,
    ZRECONFIGDISABLED = -123,
    ZSESSIONCLOSEDREQUIRESASLAUTH = -124,
    ZTHROTTLEDOP = -127

};
enum ZooSaslState
{
    ZOO_SASL_INITIAL,
    ZOO_SASL_INTERMEDIATE,
    ZOO_SASL_COMPLETE,
    ZOO_SASL_FAILED
};
enum ZooWatcherType
{
    ZWATCHTYPE_CHILD = 1,
    ZWATCHTYPE_DATA = 2,
    ZWATCHTYPE_ANY = 3
};
